# Generated by Django 6.0.1 on 2026-01-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_cart_id"),
        ("product", "0003_alter_product_options_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
