# Generated by Django 6.0.1 on 2026-01-30 12:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
            preserve_default=False,
        ),
    ]
