# Generated by Django 6.0.1 on 2026-01-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
